<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);1591;xUnit1051</NoWarn>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SeedBomb.Bulk/SeedBomb.Bulk.csproj" />
    <ProjectReference Include="../SeedBomb.Core/SeedBomb.Core.csproj" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>
