<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DataGen.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
