<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DataGen.Bulk/DataGen.Bulk.csproj" />
    <ProjectReference Include="../DataGen.Core/DataGen.Core.csproj" />
    <PackageReference Include="xunit.v3" />

    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>
