<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <!-- Test methods don't require XML doc comments -->
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DataGen.Core/DataGen.Core.csproj" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Moq" />
  </ItemGroup>
</Project>
