<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);1591;xUnit1051</NoWarn>
    <NuGetAudit>False</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DataGen.Web/DataGen.Web.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Moq" />
    <PackageReference Include="bunit" />
  </ItemGroup>
</Project>
