<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DataGen.Web/DataGen.Web.csproj" />
    <PackageReference Include="xunit.v3" />

    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Moq" />
    <PackageReference Include="bunit" />
  </ItemGroup>
</Project>
